name: deploy (dev)

# on:
#   push:
#     branches: main

on:
  pull_request:
      types: [opened, reopened, synchronize]
      branches:
          - main

jobs:

  approve-deployment:
    type: approval
  
  build:
    runs-on: ubuntu-latest
    requires: approve-deployment
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: log in to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: extract tag name
        id: tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/emmer:dev
          build-args: TAG=dev